# Generated by Django 5.0 on 2023-12-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeAssistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradeAssistant.grade'),
        ),
    ]
