# Generated by Django 5.0 on 2023-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeAssistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grades',
            field=models.ManyToManyField(blank=True, to='GradeAssistant.grade'),
        ),
    ]
